version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: contact_management_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: contact_management
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - contact_management_network

  app:
    build: .
    container_name: contact_management_app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/contact_management?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    networks:
      - contact_management_network

volumes:
  mysql_data:

networks:
  contact_management_network:
    driver: bridge 